controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz

        use_sim_time: true

        position_controller:
            type: position_controllers/JointGroupPositionController

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster



position_controller:
    ros__parameters:
        joints:
            - arm_1_joint
            - arm_2_joint
            - arm_3_joint
            - arm_4_joint
            - arm_5_joint
            - arm_6_joint
            - arm_finger_left_joint
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity

